### Variables for different environments
@baseUrl = http://localhost:3000
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoiMiIsImVtYWlsIjoibmV3dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTczODk0ODIzMywiZXhwIjoxNzM5MDM0NjMzfQ.MDqjFKsQkLG0fWe4ZtRAnsCeUESJMXSvfuDu5lj5tmI
@verificationToken = 

### Login Customer
# @name login
POST {{baseUrl}}/api/v1/customer/login
Content-Type: application/json

{
    "email": "sainyi@gmail.com",
    "password": "sainyi"
}

### Update authToken with login response
@authToken = {{login.response.body.token}}

### Create Deposit Transaction
POST {{baseUrl}}/api/v1/transactions/deposit
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "accountNo": "1739632687033920",
    "amount": 100.00,
    "description": "Deposit for savings"
}


### Get Deposit Transactions`
GET {{baseUrl}}/api/v1/transactions/deposit
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Create Withdrawal Transaction
POST {{baseUrl}}/api/v1/transactions/withdrawal
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "accountNo": "1739629409954958",
    "amount": 50.00,
    "description": "Withdrawal for savings"
}


### Get withdrawal Transactions`
GET {{baseUrl}}/api/v1/transactions/withdrawal
Authorization: Bearer {{authToken}}
Content-Type: application/json

### GET all transactions
GET {{baseUrl}}/api/v1/transactions
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Withdraw Funds
POST {{baseUrl}}/api/v1/transactions/withdrawal
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "transactionId": "12345",
    "accountNo": "1738856250480251",
    "amount": 50.00,
    "description": "Withdrawal for savings"
}


### Upload File
POST {{baseUrl}}/api/v1/transactions/file
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="transactionId"

12345
--boundary123
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

< ./example.jpg
--boundary123--



### Create Trade Request
POST {{baseUrl}}/api/v1/trade-request
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "customerId": 2,
  "accountId": 2,
  "tradeType": "SHORT",
  "period": 30,
  "accountNo": "1738856250480251",
  "tradeQuantity": 100
}


### Create Trade Success Request
POST {{baseUrl}}/api/v1/trade-success
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "tradeId": 1,
  "customerId":2
}

### Get All Trade
GET {{baseUrl}}/api/v1/trade
Authorization: Bearer {{authToken}}
Content-Type: application/json